
(function(){"use strict";
const state={data:null,user:{name:"Wittanee",team:"Credit Analyst"},xp:0,mission:0,sound:true};
const $=id=>document.getElementById(id);
function esc(v){return String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));}
function toast(msg){const t=$("toast");t.textContent=msg;t.classList.remove("hidden");setTimeout(()=>t.classList.add("hidden"),1800);}
function beep(type="ok"){if(!state.sound)return;try{const ctx=new (window.AudioContext||window.webkitAudioContext)();const o=ctx.createOscillator();const g=ctx.createGain();o.connect(g);g.connect(ctx.destination);o.frequency.value=type==="bad"?180:620;g.gain.setValueAtTime(.06,ctx.currentTime);g.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+.16);o.start();o.stop(ctx.currentTime+.16);}catch(e){}}
function badge(){if(state.xp>=75)return"Credit Master";if(state.xp>=55)return"Senior CA";if(state.xp>=30)return"Detective";return"Junior";}
function sidebar(active){const items=[["home","🏠 หน้าหลัก"],["mission","📋 ภารกิจ"],["case","📁 แฟ้มเคส"],["tips","💡 Tips"],["dash","📊 Dashboard"]];return `<aside class="sidebar"><div class="avatar">🕵️‍♀️</div><b>CA Learning Platform</b><small>PRO v2</small><div class="menu">${items.map(([k,l])=>`<button data-page="${k}" class="${active===k?"active":""}">${l}</button>`).join("")}</div><div class="help"><b>Credit Manager</b><p>ตรวจให้รอบคอบก่อนตัดสินใจนะคะ</p><button class="whiteBtn" data-action="managerTip">ขอคำแนะนำ</button><button class="whiteBtn" data-action="toggleSound">${state.sound?"🔊 Sound On":"🔇 Sound Off"}</button></div></aside>`;}
function shell(content,active="home"){$("app").innerHTML=`<div class="app">${sidebar(active)}<main class="main"><div class="topbar"><div class="brand"><small>CA LEARNING PLATFORM</small><h1>Credit Investigation Simulator PRO v2</h1><p>Observe → Analyze → Decide → Justify</p></div><div class="userbox"><span class="face">👩‍💼</span><div><b>${esc(state.user.name)}</b><br><small>${esc(state.user.team)}</small></div><span class="level">Level ${Math.max(1,Math.floor(state.xp/30)+1)}</span></div></div>${content}</main></div>`;bindEvents();}
function stats(){return `<section class="stats"><div class="stat"><span class="ico">⭐</span><div><b>${state.xp}</b><span>XP</span></div></div><div class="stat"><span class="ico">📋</span><div><b>${state.mission+1}/${state.data.missions.length}</b><span>Mission</span></div></div><div class="stat"><span class="ico">🏅</span><div><b>${badge()}</b><span>Badge</span></div></div><div class="stat"><span class="ico">🔥</span><div><b>PRO</b><span>Mode</span></div></div></section>`;}
function home(){const c=state.data.case;const progress=state.data.missions.map((m,i)=>`<div class="progressItem ${i<state.mission?"done":""}"><span>${i+1}. ${esc(m.thaiTitle)}</span><b>${i<state.mission?"100%":"0%"}</b></div>`).join("");const flow=state.data.missions.map((m,i)=>`<div class="flowStep ${i===state.mission?"active":""}"><div class="big">${m.icon}</div><b>${i+1}. ${esc(m.thaiTitle)}</b><p>${i===state.mission?"กำลังทำ":"รอปลดล็อก"}</p></div>`).join("");shell(`${stats()}<section class="hero"><div class="card caseHero"><div class="caseWrap"><div><span class="badge">เคสใหม่!</span><h2>คุณได้รับมอบหมายเคสใหม่</h2><div class="caseTitle">${esc(c.id)}</div><p>ลูกค้าขอเช่าซื้อ ${esc(c.vehicle)}<br>วงเงิน <b style="color:#075fd3">${esc(c.amount)}</b></p><p>📅 กำหนดส่ง: <b style="color:red">${esc(c.deadline)}</b></p><button class="greenBtn" data-action="join">📁 รับเคสและเริ่มการสืบสวน</button></div><div class="illustration"><div class="bubble">อย่ารีบอนุมัติ อ่านแฟ้มก่อนนะคะ!</div><div class="folder">📁</div><div class="detective">👩‍💼</div></div></div></div><aside><div class="card"><div class="managerHead">👨‍💼 Credit Manager</div><p>ภารกิจของคุณคือคิดเหมือน Credit Analyst ไม่ใช่แค่ตอบข้อสอบ</p></div><div class="card"><h3>ความคืบหน้า Mission</h3>${progress}</div></aside></section><section class="card"><h3>เส้นทางการสืบสวน</h3><div class="flow">${flow}</div></section><section class="panels"><div class="card"><h3>Top Investigator</h3><p>🥇 Nattapong 1,680 XP</p><p>🥈 Wittanee 1,450 XP</p><p>🥉 May 1,250 XP</p></div><div class="card"><h3>Competency</h3><p>Data Analysis 90%</p><p>Document Review 85%</p><p>KYC 80%</p></div><div class="card"><h3>Achievement</h3><p>🏅 First Case</p><p>🔎 Detail Inspector</p><p>🛡️ KYC Explorer</p></div></section>`,"home");}
function join(){const teams=["Credit Analyst","Team Operation BKK","Team Operation R6","Credit","Sales","บางแค","บางนา","หลักสี่","นนทบุรี","อื่นๆ"];shell(`<section class="join card"><h2>เข้าร่วมภารกิจ</h2><p>กรอกเฉพาะชื่อและทีม เพื่อเริ่มเล่นเร็วที่สุด</p><div class="form"><input id="name" placeholder="ชื่อผู้เล่น" value="${esc(state.user.name)}"><select id="team">${teams.map(t=>`<option ${t===state.user.team?"selected":""}>${esc(t)}</option>`).join("")}</select><button class="blueBtn" data-action="start">เริ่มภารกิจ</button></div></section>`,"mission");}
function caseFile(){const rows=Object.entries(state.data.case.customer).map(([k,v])=>`<div class="row"><b>${esc(k)}</b><span>${esc(v)}</span></div>`).join("");shell(`<section class="card"><h2>📁 แฟ้มเคส ${esc(state.data.case.id)}</h2><p>${esc(state.data.case.title)}</p><div class="profileTable">${rows}</div></section>`,"case");}
function profileBlock(){const rows=Object.entries(state.data.case.customer).map(([k,v])=>`<div class="row"><b>${esc(k)}</b><span>${esc(v)}</span></div>`).join("");return `<div class="card"><h3>ข้อมูลเบื้องต้นของลูกค้า</h3><div class="profileTable">${rows}</div></div>`;}
function mission(){const m=state.data.missions[state.mission];const actionHtml=m.actions.map((a,i)=>`<label class="option"><input type="radio" name="action" value="${i}"><span>${esc(a)}</span></label>`).join("");const reasonHtml=m.reasons.map((r,i)=>`<label class="option"><input type="checkbox" name="reason" value="${i}"><span>${esc(r)}</span></label>`).join("");const visual=`<div class="visualDoc"><div class="scene"><span class="mainEmoji">${m.visual[0]}</span><span class="subEmoji s1">${m.visual[1]}</span><span class="subEmoji s2">${m.visual[2]}</span><span class="subEmoji s3">${m.visual[3]}</span><span class="subEmoji s4">${m.visual[4]}</span></div><h3>เอกสารที่เกี่ยวข้อง</h3><p>ตรวจข้อมูลให้ครบก่อนเลือกการดำเนินการ</p></div>`;shell(`${stats()}<section class="card"><span class="badge">${m.icon} Mission</span><h2>${state.mission+1}. ${esc(m.thaiTitle)}</h2><p>${esc(m.story)}</p></section><section class="missionGrid"><div>${m.showCustomerProfile?profileBlock():""}${visual}</div><div class="card"><h3>Step 1: เลือกการดำเนินการ</h3><p>${esc(m.actionQuestion)}</p>${actionHtml}<h3>Step 2: เลือกเหตุผลประกอบ</h3><p>${esc(m.reasonQuestion)}</p>${reasonHtml}<div id="feedback"></div><button class="blueBtn" data-action="submit">บันทึกและดำเนินการต่อ ➜</button><button class="whiteBtn" data-action="hint">💡 Hint</button></div></section>`,"mission");}
function submitMission(){const m=state.data.missions[state.mission];const action=document.querySelector('input[name="action"]:checked');const reasons=[...document.querySelectorAll('input[name="reason"]:checked')].map(x=>Number(x.value));if(!action||reasons.length===0){toast("กรุณาเลือกการดำเนินการและเหตุผลก่อน");beep("bad");return;}let pts=0;if(Number(action.value)===m.bestAction)pts+=5;const hit=reasons.filter(x=>m.bestReasons.includes(x)).length;const wrong=reasons.filter(x=>!m.bestReasons.includes(x)).length;pts+=Math.max(0,Math.round(5*hit/m.bestReasons.length)-wrong);pts=Math.max(1,pts);state.xp+=pts;beep(pts>=8?"ok":"bad");$("feedback").innerHTML=`<div class="feedback ${pts>=8?"good":""}"><b>👨‍💼 Credit Manager Feedback</b><p>คุณได้รับ <b>${pts}/10 XP</b></p><p>${esc(m.feedback)}</p><p><b>Credit Tip:</b> ${esc(m.tip)}</p></div>`;const btn=document.querySelector('[data-action="submit"]');btn.textContent=state.mission===state.data.missions.length-1?"ไปสรุปผล":"Mission ถัดไป";btn.dataset.action="next";}
function finalPage(){shell(`<section class="card"><h2>🏁 สรุปผลการสืบสวน</h2>${stats()}<textarea id="rec" placeholder="สรุป Recommendation ของคุณต่อ Credit Manager"></textarea><br><br><button class="blueBtn" data-action="save">บันทึกผล</button><button class="whiteBtn" data-action="home">กลับหน้าแรก</button></section>`,"dash");}
function saveResult(){const data=JSON.parse(localStorage.getItem("cis_pro_v2_results")||"[]");data.push({name:state.user.name,team:state.user.team,xp:state.xp,badge:badge(),date:new Date().toISOString()});localStorage.setItem("cis_pro_v2_results",JSON.stringify(data));toast("บันทึกผลเรียบร้อย");dashboard();}
function dashboard(){const data=JSON.parse(localStorage.getItem("cis_pro_v2_results")||"[]").sort((a,b)=>b.xp-a.xp);const avg=data.length?Math.round(data.reduce((s,x)=>s+x.xp,0)/data.length):0;const rows=data.map(d=>`<tr><td>${esc(d.name)}</td><td>${esc(d.team)}</td><td>${d.xp}</td><td>${esc(d.badge)}</td></tr>`).join("");shell(`<section class="card"><h2>📊 Dashboard</h2><section class="stats"><div class="stat"><span class="ico">👥</span><div><b>${data.length}</b><span>ผู้เล่น</span></div></div><div class="stat"><span class="ico">⭐</span><div><b>${avg}</b><span>XP เฉลี่ย</span></div></div><div class="stat"><span class="ico">🏆</span><div><b>${data[0]?esc(data[0].name):"-"}</b><span>Top</span></div></div><div class="stat"><span class="ico">📈</span><div><b>PRO</b><span>Status</span></div></div></section><table class="table"><tr><th>ชื่อ</th><th>ทีม</th><th>XP</th><th>Badge</th></tr>${rows}</table><br><button class="whiteBtn" data-action="clear">ล้างข้อมูล Demo</button></section>`,"dash");}
function tips(){shell(`<section class="card"><h2>ความรู้ & Tips</h2><div class="flow"><div class="flowStep"><div class="big">🔎</div><b>ตรวจให้รอบคอบ</b><p>อย่าดูแค่เอกสารครบ</p></div><div class="flowStep"><div class="big">🧠</div><b>คิดเป็นระบบ</b><p>Observe → Analyze → Decide</p></div><div class="flowStep"><div class="big">📌</div><b>Verify ก่อน</b><p>ยังไม่มั่นใจอย่ารีบอนุมัติ</p></div></div></section>`,"tips");}
function bindEvents(){document.querySelectorAll("[data-page]").forEach(btn=>btn.addEventListener("click",()=>{const p=btn.dataset.page;if(p==="home")home();if(p==="mission")mission();if(p==="case")caseFile();if(p==="tips")tips();if(p==="dash")dashboard();}));document.querySelectorAll("[data-action]").forEach(btn=>btn.addEventListener("click",()=>{const a=btn.dataset.action;if(a==="join")join();if(a==="start"){state.user.name=$("name").value||"Wittanee";state.user.team=$("team").value;mission();}if(a==="submit")submitMission();if(a==="next"){if(state.mission<state.data.missions.length-1){state.mission++;mission();}else finalPage();}if(a==="save")saveResult();if(a==="home")home();if(a==="clear"){localStorage.removeItem("cis_pro_v2_results");dashboard();}if(a==="hint")toast("Hint: เลือกสิ่งที่มีผลต่อความเสี่ยงและการชำระหนี้ก่อน");if(a==="managerTip")toast("Credit Manager: อย่ารีบตัดสินใจ ให้ดูเหตุผลและข้อมูลรองรับก่อนค่ะ");if(a==="toggleSound"){state.sound=!state.sound;home();}}));}
async function init(){try{const res=await fetch("data/missions.json");state.data=await res.json();home();}catch(err){$("app").innerHTML=`<div class="card" style="max-width:800px;margin:80px auto"><h1>โหลดระบบไม่สำเร็จ</h1><p>${esc(err.message)}</p></div>`;}}
document.addEventListener("DOMContentLoaded",init);
})();
